### ISSUE TITLE
Use a builder instead of child in AnimatedBookWidget

### ISSUE THREAD

**Issue by ecarlosdev** [the-d-velopers/animated_book_widget#18]
What do you think about this?

```dart
AnimatedBookWidget(
    cover: cover,
    contentBuilder: (context, bookAnimation, child) {
        return SizedBox.expand(
            child: Transform(
                alignment: Alignment.center,
                transform: Matrix4.identity()
                    ..scale(bookAnimation.value),
                child: child,
            ),
        );
    },
    contentChild: ColoredBox(color: color),
    size: const Size.fromWidth(160),
)
```

If a default animation is needed, it could be build on top of this or we could use a factory

**Comment by br-programmer** [comment]
"I like the proposal, which one does @diegoveloper, @monster555, or @Adrianns  say?"

**Comment by Adrianns** [comment]
It seems like a more efficient way to render it and avoid unnecessary re-renders

**Comment by diegoveloper** [comment]
yeah, that's nice, we should give the developer the option to choose between "content" and "contentBuilder", also we should add an `assert to make sure we can't set both at the same time.

**Comment by monster555** [comment]
Looks good to me. 
Quick question, would we only have `contentBuilder` or would we have another `builder`?

**Comment by diegoveloper** [comment]
hey @ecarlosdev what's your discord username/name?

**Comment by ecarlosdev** [comment]
> hey @ecarlosdev what's your discord username/name?

Es karlosz

**Comment by diegoveloper** [comment]
> > hey @ecarlosdev what's your discord username/name?
> 
> Es karlosz

are you going to open a PR for this issue?

**Comment by br-programmer** [comment]
Completed on #23
