### ISSUE TITLE
Do we really need lists?

### ISSUE THREAD

**Issue by ecarlosdev** [the-d-velopers/animated_book_widget#27]
I think the main value of this package is in the animated book (until now). Don't you feel like the lists don't add much?

Besides, it's just one more thing to maintain.

**Comment by diegoveloper** [comment]
I think you are right, we can let the user to decide if they want to use `AnimatedBookList` to build a list of `AnimatedBookWidget`,  or if they want to just use the `AnimatedBookWidget` as individual widget.

What do you think? @br-programmer @monster555 ?  We would name examples as individual widgets.

**Comment by ecarlosqm** [comment]
> I think you are right, we can let the user to decide if they want to use `AnimatedBookList` to build a list of `AnimatedBookWidget`, or if they want to just use the `AnimatedBookWidget` as individual widget.
> 
> What do you think? @br-programmer @monster555 ? We would name examples as individual widgets.

I meant to completely remove AnimatedBookList 😅

**Comment by diegoveloper** [comment]
hmmmm , yeah the `AnimatedBookList` is too simple, it's just a wrapper of a ListView or GridView, but on the examples it's ok that we show how it works in a ListView.

@br-programmer Can you make that change? or what do you think?

**Comment by br-programmer** [comment]
So, it would no longer be called animatedBookList; instead, it would be called AnimatedBookWidget.

**Comment by diegoveloper** [comment]
> So, it would no longer be called animatedBookList; instead, it would be called AnimatedBookWidget.

Yeah, I can rename the repository name, can you rename the package/folder?

**Comment by br-programmer** [comment]
Okay, I'll change it. I just need you to tell me how it should be!

**Comment by diegoveloper** [comment]
`animated_book_widget`

**Comment by monster555** [comment]
LGTM... Closing as resolved in #30
